### ISSUE TITLE
Objective-C support

### ISSUE THREAD

**Issue by ChrisMash** [shaps80/Peek#10]
It would be great if the pod could be used in Objective-C projects. As far as I can tell you just need to add @objc to the relevant classes, which might just be the Peek class?

**Comment by shaps80** [comment]
Actually the Peek.swift class is an NSObject class for that reason -- Peek already supports Obj-C projects. :)

**Comment by shaps80** [comment]
I just loaded up a quick sample project with Peek included -- and everything works as expected. This was always supported.

I've attached the sample here so you can see it working ;)

[Peek-ObjC-Sample.zip](https://github.com/shaps80/Peek/files/239351/Peek-ObjC-Sample.zip)

<img width="1136" alt="screen shot 2016-04-27 at 21 40 21" src="https://cloud.githubusercontent.com/assets/251310/14867505/bacc19d2-0cc0-11e6-8cdd-d0f681ef4fa7.png">

**Comment by shaps80** [comment]
There was actually an issue with iOS 8 project so...

I fixed the issues and now have full iOS 8.0+ and Obj-C support! :)

Please run pod update to get v2.1.0 which includes this support.

If you have any further issues, please let me know -- thanks :)

**Comment by ChrisMash** [comment]
Thanks for looking into it and getting it sorted!
