### ISSUE TITLE
iOS 7 not supported?

### ISSUE THREAD

**Issue by linktoming** [shaps80/Peek#11]
Just now tried to integrated peek into my project then was told by `pod install` that 
```
[!] Unable to satisfy the following requirements:

- `Peek` required by `Podfile`

Specs satisfying the `Peek` dependency were found, but they required a higher minimum deployment target.
```

You might considering make the system support section in read me more explicit about not supporting iOS 7 :)

**Comment by shaps80** [comment]
Well I figured the statement in the README that says, supported on iOS8+ was clear ;)
I wouldn't generally state all the non-supported versions. Thanks for feedback though ;)
