### ISSUE TITLE
Not working with Objective- C project IOS Target 8.3

### ISSUE THREAD

**Issue by ajaybeniwal** [shaps80/Peek#12]
I have added peek module to my objective c app but the module is not providing any overlap on double tap of any ui control.

I have also added shake gesture which is called on shake but the peek is not working.

```
#pragma mark - UIApplication delegate methods
- (void)motionBegan:(UIEventSubtype)motion withEvent:(UIEvent *)even
{
    [self.window.peek handleShake:motion];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
self.window.peek.enabled = YES;
}
```

**Comment by shaps80** [comment]
Here's a working sample. Maybe you can narrow down the issue? https://github.com/shaps80/Peek/files/239351/Peek-ObjC-Sample.zip

**Comment by shaps80** [comment]
So, I fixed the issues and now have full iOS 8.0+ and Obj-C support! :)

Please run `pod update` to get v2.1.0 which includes this support.

If you have any further issues, please let me know -- thanks :)

**Comment by ajaybeniwal** [comment]
I bumped the target to 9.0 and updated the pod to 2.1.0 but still it is not working in my objective c app any special thing i need to handle or do

**Comment by shaps80** [comment]
[Peek-ObjC-Sample.zip](https://github.com/shaps80/Peek/files/243046/Peek-ObjC-Sample.zip)

Can you please try running this project and tell me if it works for you -- try both iOS 8.3 and iOS 9 simulators. For me, this works perfectly. There WAS a problem previously, but I resolved it in 2.1.0

**Comment by ajaybeniwal** [comment]
The sample project is not building at all 

The file “SwiftLayout.xcconfig” couldn’t be opened because there is no such file. (/Users/ajasingh/Downloads/PeekSample/Pods/Target Support Files/SwiftLayout/SwiftLayout.xcconfig)
error: unable to read module map contents from 'Target Support Files/SwiftLayout/SwiftLayout.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “SwiftLayout.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/ajasingh/Downloads/PeekSample/Pods/Target Support Files/SwiftLayout/SwiftLayout.modulemap, NSUnderlyingError=0x7fdd14154130 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
error: unable to read module map contents from 'Target Support Files/SwiftLayout/SwiftLayout.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “SwiftLayout.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/ajasingh/Downloads/PeekSample/Pods/Target Support Files/SwiftLayout/SwiftLayout.modulemap, NSUnderlyingError=0x7fdd18197bd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by shaps80** [comment]
Ahh I must have accidentally included SwiftLayout as a local pod.
Let me add a new sample for you.

**Comment by shaps80** [comment]
[Peek-ObjC-Sample.zip](https://github.com/shaps80/Peek/files/244354/Peek-ObjC-Sample.zip)

Ok, try this one -- sorry for the mess up.

**Comment by ajaybeniwal** [comment]
The sample is working but i do not know the reason my project is not working may be some flag or some issue I will dive deeply to check what could be the issue

**Comment by shaps80** [comment]
Yes please -- as you can see, it works for me and others. Would be great to understand what's different in your project.

Thanks for the feedback.

**Comment by ajaybeniwal** [comment]
I Have spent a lot of time to figure why it does not work in my legacy objective-c project but still it does not work ,  I am giving up now and will try to use is some future projects  thanks for your time

**Comment by shaps80** [comment]
Sorry I can't be more help without actually seeing the project. 

Thanks for your feedback, good luck in the future ;)

**Comment by ajaybeniwal** [comment]
Sorry for the trouble again I cannot provide the source code since it is company project where I work.
It is a significant request but is it possible for you to connect remotely and see what could be the issue because you might have faced some issue while making project compatible to Objective -c

**Comment by shaps80** [comment]
To be honest, I had no issues with running this with an Obj-C project and have had reports from other people without issue too. You are the only report so far, that's having a problem.

How are you including the project? Cocoapod of directly into your project?

I don't really have the time at the moment, to connect remotely and fix it, but happy to continue this line of help and see if we can get you going. If not, maybe I can try over the weekend via remote access.

**Comment by ajaybeniwal** [comment]
You are absolutely correct it works fine in Obj-C project even i created fresh  Objective C project and it worked its only my legacy project that is not working I dont know why , I have included it using CocoaPods , Anyways  Thanks for your help I will give it one more shot before weekend and if I you have time over weekend we can remote access. It is really an awesome product thats why i wanted to intergrate into our APP to help our Quality assurance and designer team.
