### ISSUE TITLE
Counld change immediately？

### ISSUE THREAD

**Issue by codwam** [shaps80/Peek#13]
Counld change text, font, color etc... immediately？

**Comment by shaps80** [comment]
Sorry I don't understand. You want to change the look and feel of Peek?

**Comment by codwam** [comment]
Change the label's text, font, color etc...  on the simulator or iPhone

**Comment by shaps80** [comment]
Sorry mate, that's not any clearer to me. Can you please explain in more detail?

**Comment by codwam** [comment]
I want to in your inspector change the font size

**Comment by shaps80** [comment]
Ah I see, you find the UI difficult to read? Shouldn't be too difficult. I think I could probably provide the option when you configure other peek options. 
Thanks for feedback

**Comment by codwam** [comment]
No, I didn't.
I only want to change the color or text in the Peek so that the original label color or text changed too?
my english is weak , sorry

**Comment by shaps80** [comment]
ahh you mean to modify your app?

Peek is NOT an editing tool and will never be I'm afraid. Its an inspection tool, used to determine issues, validate against specifications, etc..

You are welcome to Fork the project and add this yourself, but I have no plans to build this kind of feature into Peek I'm afraid.

Thanks.
