### ISSUE TITLE
Pod not integrating...

### ISSUE THREAD

**Issue by janzawadzki** [shaps80/Peek#14]
Xcode 7.3.1.  Using other pods in the project just fine - added Peek, went through the pod deintegrate, pod install cycle, clean, build.  Everything else works but Peek - window?.peek.enabled = true in AppDelegate fails with **Value of type UIWindow has no member peek**.

I can see the extension code in pods just fine.  Alamofire and a couple of other pods are working just fine.  Anyone come across this??

**Comment by shaps80** [comment]
Have you possibly forgotten 

`import Peek`
