### ISSUE TITLE
Swift 2.3 or Swift 3 Support

### ISSUE THREAD

**Issue by mackoj** [shaps80/Peek#15]
Hi,

Thanks for your great tool. It would be great if it could support Swift 2.3 or Swift 3 ?

Cheers,

**Comment by shaps80** [comment]
This is currently being working on. You should hopefully see it shortly :)

**Comment by huguesbr** [comment]
Could you re-open this issue until it's fix? Almost submitted a new one.. I guess we can consider it's not fix until done, correct?

**Comment by shaps80** [comment]
Agreed -- I'm not sure why I closed this ;)

Please feel free to contribute 👍

**Comment by huguesbr** [comment]
Trying (at least for `2.3`) but having some issue doing a clean PR on InkKit.. Can't set base PR branch to a tag!? (see: https://github.com/shaps80/InkKit/pull/5)

**Comment by shaps80** [comment]
I understand.  Not that i will never both to formally support 2.3 since no further Xcode versions will support it. 

Shaps

**Comment by huguesbr** [comment]
@shaps80 yep I know XCode 8.2 is last Swift 2.3 support :( I thought Obj-C was dead :P. I love all my Obj-C pods right now :). I think having Swift 2.3 supporting branches (but not keep up to date) is nice. Will try my best.

**Comment by huguesbr** [comment]
@shaps80 ask and you shall receive... https://github.com/shaps80/Peek/pull/16. Except issue with not being able to point to the correct branch on the PR (as there is not branch for the base branch on which I did my changes, ...).. Hope it's clear.

**Comment by anneWe** [comment]
Hi, is there any Swift 3 support planned? I really like this tool and would love to use it in my Swift 3 projects too.

**Comment by shaps80** [comment]
Absolutely. However my wife and I just had a baby a few days ago so I couldn't say how long it'll be before I find the time. 

You're more than welcome to submit a PR ;-)

Shaps

**Comment by shaps80** [comment]
`pod 'Peek', '2.3'`

Thanks to @huguesbr for his help getting this out -- sorry for the delays.

**Comment by shaps80** [comment]
@anneWe @huguesbr @mackoj Just letting you all know...

Swift 4 will be officially supported this week!
Thank you for supporting the project.
