### ISSUE TITLE
Peek 3.0

### ISSUE THREAD

**Issue by shaps80** [shaps80/Peek#17]
While planning for a 3.0 feature set, I thought it best to get some feedback from the open source community.

Wondering how many of you use Peek and whether or not you're finding it useful?
Looking for ideas about improvements, where its been most useful and what doesn't work or is missing?

_Any_ input appreciated 👍

**Comment by skytoup** [comment]
I crate a pull request with upgrade to swift 3.1 . In here: <https://github.com/shaps80/Peek/pull/18>

**Comment by skytoup** [comment]
@shaps80 I crate a pull request with upgrade to swift 3.1 . In here: <https://github.com/shaps80/Peek/pull/18>
