### ISSUE TITLE
Totally broken on Xcode 9.2

### ISSUE THREAD

**Issue by DanielAsher** [shaps80/Peek#20]
Looks like this project is deprecated. Would be nice to have this recorded in the readme.

So much work, so well done - I do appreciate the ambition!

best of luck,

Daniel

**Comment by shaps80** [comment]
Actually, great news. Swift 4 and Xcode 9.2+ are now fully supported. I worked past the issues and now have a working build again. 

Look for an update soon 👍

Thank you for supporting this project.

**Comment by DanielAsher** [comment]
👌

**Comment by shaps80** [comment]
FYI MAJOR update coming out this week. Follow my twitter account for updates!

@shaps
