### ISSUE TITLE
Pressing volume key doesn't open peek

### ISSUE THREAD

**Issue by askari01** [shaps80/Peek#23]
iOS: 11.2.6
Xcode: 9.2
deploy: iOS 9
device: SE
swift: 4.0

program: example (pull date 23march 18) branch master

**Comment by shaps80** [comment]
I think the example project uses a shake. It’s configured in AppDelegate.swift. But totally agree I should change that. 

Thanks! Hoe you like the tool.

**Comment by shaps80** [comment]
Fixed :)

**Comment by askari01** [comment]
thank you
