### ISSUE TITLE
Is this similar to FLEX?

### ISSUE THREAD

**Issue by pjebs** [shaps80/Peek#3]
https://github.com/Flipboard/FLEX

**Comment by shaps80** [comment]
Well I released the original version before Flex came about, so there may be some overlap.

However there's a considerable difference, both in how I present details and also that Peek is read-only.

Its designed as a testing tool for getting the 'truth' about the current state of your app/component. Both tools allow you to inspect properties, etc.. however Peek also has sophisticated reporting tools for communicating back to the development team.

**Comment by pjebs** [comment]
When will an alpha version come out?

**Comment by shaps80** [comment]
Apologies for such a delayed release. But it's available now ;)
