### ISSUE TITLE
iOS8 support

### ISSUE THREAD

**Issue by tbaranes** [shaps80/Peek#5]
Hey! 

Seems to be an awesome framework, but is there any reason to target iO S8.2 instead of 8.0?

**Comment by shaps80** [comment]
For the release I had some issues around measuring text. It's now fixed and will be included in the next update :-)

**Comment by tbaranes** [comment]
Awesome! Looking forward for that release 🎉

**Comment by CallumOz** [comment]
The latest release 2.0.1, still doesn't support iOS 8.0.
Is it maybe the next version that will support iOS 8.0 ?

**Comment by tbaranes** [comment]
Hopins so 👯

**Comment by shaps80** [comment]
Ahh actually it does but I forgot to update the podspec. I'll update tomorrow. Thanks for reminder :-)
