### ISSUE TITLE
Peek becoming active when recording via QuickTime and can't be disabled

### ISSUE THREAD

**Issue by pgrosslicht** [shaps80/Peek#53]
Hi,

when I start screen recording an attached device in QuickTime (File -> New Movie Recording), Peek becomes active and can't be disabled with the Volume Up button until I stop the recording.

I'm using Peek v5.0.1, iOS 11.2 and QuickTime Player 10.4

Thanks!

**Comment by shaps80** [comment]
@pgrosslicht did this help?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pgrosslicht** [comment]
Yes, this did help and I was able to record it, thanks, but since this is just a workaround and not real fix I suggest not closing this issue, in case other people have the same issue.

**Comment by shaps80** [comment]
I didn’t close it 👍🏻

Unfortunately I’m not sure there’s a fix. I might update the ReadMe with known issues/caveats to reflect this and other issues that arise. 

Thanks for letting me know. Glad you were able to get it working.

**Comment by pgrosslicht** [comment]
I think a possible fix for devices on iOS 11+ would be to listen to the `UIScreenCapturedDidChange` notification and disable the trigger when capture started. If this sounds reasonable to you I'll try implementing it and send a PR if it works.

**Comment by shaps80** [comment]
So far I have feature parity across iOS 9+ but I agree it would be nice to have a fix even just for iOS 11+.
Are you suggesting we switch over to a shake gesture while screen capturing is in progress and then back again once its completed? I'd be cool with that, better than having to re-compile/run again.
I'm curious if that notification is triggered by Quicktime as well? I thought that was only applicable when recording on the device?
If I'm wrong (and totally hope I am) this is a great idea IMHO. PR away! 👍

**Comment by shaps80** [comment]
Quick suggestion on the implementation. If you do it as an extension on UIScreen and implement an identical API to the iOS 11 approach, then you can use Swift's availability APIs to use iOS 11's built-in approach on iOS 11, and fallback to the above for older iOS versions. 

So inside that condition above, you'd just manually post a `UIScreenCapturedDidChange` notification with the `UIScreen` instance. And if you add `.isCaptured` or wateva the iOS 11 API is to that, we can query it the same way. This way Peek's code is always using the more modern API and when iOS 11 is the minimum target in the future, I can just delete the extension.

**Comment by pgrosslicht** [comment]
The problem with the extension method is, that when I implement `isCaptured` in the extension I can't call the original variable anymore, only my own implementation. And I can't mark it as unavailable for iOS 11 because unavailable doesn't take a version. Any ideas?

**Comment by shaps80** [comment]
Fair enough. What about something simpler:

```swift
internal var peek_isCapturing: Bool { }
```

Still on `UIScreen` but inside that you can check the current version and either return the iOS API result or do our check.

**Comment by shaps80** [comment]
@pgrosslicht where are we at with your PR?

**Comment by pgrosslicht** [comment]
Mostly done, but there seems to be a timing issue where Peek activates before I can disable the activation.  Haven't gotten around to look into it but I'll get to it this weekend.

**Comment by shaps80** [comment]
If there are not further updates to this, I'd like to close it off?
