### ISSUE TITLE
Upcoming release branch is missing

### ISSUE THREAD

**Issue by valeriyvan** [shaps80/Peek#55]
As 5.1.0 was released and branch release/5.1.0 doesn't exist, probably information in `CONTRIBUTING.md`, `pull_request_template.md` and `README.md`  is obsolete.

What now upcoming release branch will be?

**Comment by shaps80** [comment]
Yeah I was actually thinking of re-wording that to be an example rather than having to maintain it all the time. I am not sure about the next release atm but likely release/5.2.0

**Comment by valeriyvan** [comment]
Then create this branch, please. I am going to add some improvements.

**Comment by shaps80** [comment]
I already did, merged your other PR already into it as well ;)
