### ISSUE TITLE
Demo video not working

### ISSUE THREAD

**Issue by marcosgriselli** [shaps80/Peek#57]
The vimeo video on the readme and website is not loading. 
It shows an error message saying: 
### "_Sorry This video will be available for viewing shortly._". 

It's been like this for the past week at least. I want to show this tool in action to our designer before implementing it as I believe it could be really useful.

**Comment by shaps80** [comment]
@marcosgriselli this is fixed on Vimeo as well now. No idea what happened, I had to re-upload the video. Vimeo support couldn't explain it either.
