### ISSUE TITLE
Crash 'class is not key value coding-compliant for the key indicatorStyle'

### ISSUE THREAD

**Issue by valeriyvan** [shaps80/Peek#59]
2018-04-18 17:04:01.421452+0200 ********[1810:3083320] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<********.AutoCompleteTextField 0x61a0000a3280> valueForUndefinedKey:]: this class is not key value coding-compliant for the key indicatorStyle.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e6501e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010dce5031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e6500b9 -[NSException raise] + 9
	3   Foundation                          0x000000010d7d2f58 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 226
	4   Foundation                          0x000000010d6feebc -[NSObject(NSKeyValueCoding) valueForKey:] + 284
	5   Peek                                0x00000001090de201 _T04Peek13EnumAttributeC5valueypSgvg + 161
	6   Peek                                0x00000001090de0ea _T04Peek16DynamicAttributeC5valueypSgvgToTm + 26
	7   Peek                                0x0000000109123bda _T04Peek0A23InspectorViewControllerC05tableC0SbSo07UITableC0C_10Foundation9IndexPathV12canEditRowAttFTf4dgn_n + 618
	8   Peek                                0x000000010911b6ca _T04Peek0A23InspectorViewControllerC05tableC0SbSo07UITableC0C_10Foundation9IndexPathV12canEditRowAttFTo + 74
	9   UIKit                               0x0000000109afd9ce -[UITableView _canEditRowAtIndexPath:] + 97
	10  UIKit                               0x0000000109b2bfda -[UITableView _setupCell:forEditing:atIndexPath:animated:updateSeparators:] + 188
	11  UIKit                               0x0000000109b1a622 __53-[UITableView _configureCellForDisplay:forIndexPath:]_block_invoke + 4244
	12  UIKit                               0x0000000109a8fbca +[UIView(Animation) performWithoutAnimation:] + 90
	13  UIKit                               0x0000000109b194aa -[UITableView _configureCellForDisplay:forIndexPath:] + 240
	14  UIKit                               0x0000000109b11414 -[UITableView _dequeueReusableCellWithIdentifier:forIndexPath:usingPresentationValues:] + 653
	15  UIKit                               0x0000000109b11153 -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:] + 91
	16  Peek                                0x000000010913a7a3 _T04Peek0A23SectionedViewControllerC05tableC0So07UITableC4CellCSo0fC0C_10Foundation9IndexPathV12cellForRowAttFTf4ggn_n + 115
	17  Peek                                0x00000001091242c2 _T04Peek0A23InspectorViewControllerC05tableC0So07UITableC4CellCSo0fC0C_10Foundation9IndexPathV12cellForRowAttFTf4ggn_n + 658
	18  Peek                                0x000000010911960a _T04Peek0A23InspectorViewControllerC05tableC0So07UITableC4CellCSo0fC0C_10Foundation9IndexPathV12cellForRowAttFTo + 74
	19  UIKit                               0x0000000109b2c5c7 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 783
	20  UIKit                               0x0000000109b2cb44 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 74
	21  UIKit                               0x0000000109af3f0a -[UITableView _updateVisibleCellsNow:isRecursive:] + 3168
	22  UIKit                               0x0000000109b14840 -[UITableView layoutSubviews] + 176
	23  UIKit                               0x0000000109a9e808 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1515
	24  QuartzCore                          0x000000010bd0261a -[CALayer layoutSublayers] + 177
	25  QuartzCore                          0x000000010bd0682b _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	26  QuartzCore                          0x000000010bc8d29f _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 343
	27  QuartzCore                          0x000000010bcba940 _ZN2CA11Transaction6commitEv + 568
	28  QuartzCore                          0x000000010bcbb6be _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 76
	29  CoreFoundation                      0x000000010e5f2607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	30  CoreFoundation                      0x000000010e5f255e __CFRunLoopDoObservers + 430
	31  CoreFoundation                      0x000000010e5d6b81 __CFRunLoopRun + 1537
	32  CoreFoundation                      0x000000010e5d630b CFRunLoopRunSpecific + 635
	33  GraphicsServices                    0x00000001131a3a73 GSEventRunModal + 62
	34  UIKit                               0x00000001099cf0b7 UIApplicationMain + 159
	35  ********                            0x00000001073440b7 main + 55
	36  libdyld.dylib                       0x0000000111736955 start + 1
	37  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

On a try to scroll inspector down when Appearance section is going to appear:
![simulator screen shot - iphone x - 2018-04-18 at 17 05 19](https://user-images.githubusercontent.com/1630974/38940684-1414a476-432b-11e8-808b-c1a751e52ce2.png)

**Comment by shaps80** [comment]
Interesting, I haven't come across this. I'll try and find some time to investigate. Let me know if you find a solution yourself.

**Comment by shaps80** [comment]
Any profess on this? I can’t seem to reproduce. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaps80** [comment]
@valeriyvan ping ;)

**Comment by valeriyvan** [comment]
@shaps80, sorry, will look into it on Saturday.

**Comment by shaps80** [comment]
Ok I've seen this issue and worked out what it is. I had accidentally added `indicatorStyle` lookups on `UITextField` rather than `UITextView`.

I don't have time to fix this right now but I'll put it into a fix and do a release shortly.

At some point I'd like to drop the internal Objective-C support entirely and move to a keyPath based approach to remove these kinds of issues.

**Comment by shaps80** [comment]
Fixed on #58

**Comment by arctouch-pedrocosta** [comment]
@shaps80 is the update available through CocoaPods? I don't seem to be able to be able to update it through ```pod update```

**Comment by shaps80** [comment]
Oops I had indeed forgotten! Sorry about that, v5.2.0 is available via Cocoapods.
Thank you for letting me know 😬
