### ISSUE TITLE
Peek Support

### ISSUE THREAD

**Issue by Dipak113** [shaps80/Peek#6]
Can Peek support for Objective C?

**Comment by shaps80** [comment]
Peek is written completely in Swift, however it makes heavy use of the runtime and dynamic dispatch. Also, since you don't need to write more than one line of code, it should work just fine. I have tested it on multiple objective c based projects and it worked fine.

**Comment by Dipak113** [comment]
O thanks for information.So I will test Peek with Objective C projects.

**Comment by shaps80** [comment]
Let me know if you have any issues  :)
