### ISSUE TITLE
Not a member type of ...

### ISSUE THREAD

**Issue by vaklinzi** [shaps80/Peek#65]
![screen shot 2018-10-05 at 12 14 50](https://user-images.githubusercontent.com/16841490/46526926-5ca98d80-c898-11e8-9438-b2832ffc700f.png)

This is the problem I have when trying to include Peek in my project. 
My Podfile is like this:

```
pod 'Peek', :configurations => ['Debug']

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "Peek" then
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```
XCode Version 9.4.1 (9F2000)

I would be very grateful If someone give me any hint why is this happening.

**Comment by shaps80** [comment]
The latest version of Peek is Swift 4.2, which had UIKit changes so its likely the issue.

**Comment by Abeansits** [comment]
@vaklinzi you will need to upgrade your project, not the other way around. Peek already uses Swift 4.2. 
The easiest thing to do is to upgrade to Xcode 10 and follow the migration guide.

**Comment by shaps80** [comment]
@vaklinzi, @Abeansits is right – you'll need to upgrade to Xcode 10 in order to use Peek. There are previous releases that work with the version of Xcode you're using, however the current release is designed to work with Swift 4.2 (the latest release of Swift)

@Abeansits thanks for replying for me 👍 Appreciated!

**Comment by vaklinzi** [comment]
Thank you both guys, @Abeansits @shaps80 . Really appreciate the fast responses. Will update soon! Keep the good work!
