### ISSUE TITLE
Warnings with Xcode 10.1 and Swift 4.2

### ISSUE THREAD

**Issue by arctouch-pedrocosta** [shaps80/Peek#67]
Hello, is there any plan to fix the warnings associated with the Peek Pod on Xcode 10.1 and Swift 4.2? See screenshot attached. Thank you.
![screen shot 2018-11-14 at 11 19 36 am](https://user-images.githubusercontent.com/10923005/48506890-572c5500-e7ff-11e8-9cb1-c8b18240f811.png)

**Comment by shaps80** [comment]
Yes update coming soon

**Comment by arctouch-pedrocosta** [comment]
@shaps80 was this ever fixed?

**Comment by shaps80** [comment]
I thought so, I will check today. Thanks.

**Comment by SlaunchaMan** [comment]
@shaps80 Do you have a new release ready? We still have many warnings in our build.

**Comment by shaps80** [comment]
@SlaunchaMan @arctouch-pedrocosta – apologies for the long delay, had a lot on this year and this repo got neglected. Are you still requiring Xcode 10 support? I've now upgraded and removed all warnings for Xcode 11.

**Comment by shaps80** [comment]
Ok so `5.3.0` is out and fixes ALL warnings, plus updates to Xcode 11 and Swift 5.1.
For the older version you can silence those warnings by using `inhibit_warnings!` in your Podfile.

Not ideal I know but there is a new version that fixes the lot. Closing this issue now.
Thanks.
