### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by tbaranes** [shaps80/Peek#7]
Long term feature request, but if we can have that one unify library to get all these information on iOS as well as OSX, it really could be awesome, but I have notion that will ask a lot of work!

**Comment by shaps80** [comment]
Yeah I do a lot of OSX dev as well -- but its a completely different beast -- also there are a lot more built in tools for debugging layout for example on OSX. I found it less necessary. Also, I primarily work on mobile apps ;)

But definitely worth a thought. My next step is around reporting issues back to your teams via Slack integration ;)
