### ISSUE TITLE
Auto turn on when on  AVAudioRecorder is recording.

### ISSUE THREAD

**Issue by adamszeptycki** [shaps80/Peek#8]
Peek turns on when AVAudioRecorder start recording and it's impossible to turn it off. Any ideas how to solve that

**Comment by shaps80** [comment]
ah interesting -- I figured that would happen for some people -- I have an update coming tomorrow that will allow you to configure Peek on launch:

```swift
window?.peek.enableVolumeControls = false
window?.peek.enabled = true
```

Then, make sure you add the shake gesture instead. Should solve the issue for apps using the volume controls -- at least until I can solve this in a more elegant way.

**Comment by shaps80** [comment]
ok, so you run `pod update` and the latest version of Peek should fix your issue :)

**Comment by shaps80** [comment]
Did the update solve your issue? Feedback would be great thanks ,-)
